name: Example
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-20.04
    name: Save Output
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - shell: bash
        run: |
          echo ${{ github.ref }}
          echo ${BRANCH_NAME}
          expr 1 + 1 > output.log
          python3 --version
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: output.log
      - name: Echo Branch
        run: |
          echo ${{ github.ref }}
          echo ${BRANCH_NAME}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ env.BRANCH_NAME }}
          regex: '/ast/'
          flags: gm

      - name: See matches
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          echo "JIRA_TicketID is ${{steps.regex-match.outputs.match}}"
 
         
