name: Example
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-20.04
    name: Save Output
    steps:
      - shell: bash
        run: |
          echo ${{ git.ref }}
          expr 1 + 1 > output.log
          python3 --version
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: output.log
