name: A workflow to test parameter
on: 
  #schedule:
  #  - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
        branch-prefix:
          description: 'The branch prefix to use. Either feature|develop|release|hotfix|master'
          required: true
          default: ''
        team-no:
          description: 'Team number. Always required.'
          required: true
          default: ''
        ticket-id:
          description: 'Ticket ID of branch. Required on branch prefix feature and hotfix'
          required: false
          default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HERE: Lars
    defaults:
      run:
        working-directory: ./sc-app-deploy
          

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Echo parameter
        run: |
          echo "GITHUB event trigger:       ${{ github.event_name }}
          echo "GITHUB input branch-prefix: ${{ github.event.inputs.branch-prefix }}
          echo "GITHUB input team-no:       ${{ github.event.inputs.team-no }}
          echo "GITHUB input ticket-id:     ${{ github.event.inputs.ticket-id }}

      # Print the working directory and allow the execution of the sc-app-deploy.py script.
      - name: Display working directory
        run: |
          ls -la .
          env
          pwd
        shell: bash
