name: A workflow for my Hello World file
on: 
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
        ticket-id:
          description: 'Ticket ID of feature branch'
          required: false
          default: ''
        team-no:
          description: 'Team number'
          required: false
          default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo parameter
        run: |
          echo "Deploying ${{ github.event.inputs.ticket-id }} on hotfix${{ github.event.inputs.team-no }}.hpi-schul-cloud.org"
